### ISSUE TITLE
Stack file for 8.0.2

### ISSUE THREAD

**Issue by dmjio** [dmjio/miso#179]
We might be able to use these, cc @matchwood

caveat emptor https://github.com/ghcjs/ghcjs/issues/571

```yaml
resolver: lts-8.11
compiler: ghcjs-0.2.1.9008011_ghc-8.0.2
compiler-check: match-exact
setup-info:
  ghcjs:
    source:
      ghcjs-0.2.1.9008011_ghc-8.0.2:
        url: https://github.com/matchwood/ghcjs-stack-dist/raw/master/ghcjs-0.2.1.9008011.tar.gz
        sha1: a72a5181124baf64bcd0e68a8726e65914473b3b
```
