### ISSUE TITLE
miso 0.20.1.0 build failure with servant 0.14

### ISSUE THREAD

**Issue by DanBurton** [dmjio/miso#426]
As seen on the Stackage build server:

```
 [ 6 of 18] Compiling Miso.Html.Internal ( ghc-src/Miso/Html/Internal.hs, dist/build/Miso/Html/Internal.o )

ghc-src/Miso/Html/Internal.hs:126:8: error:
    • Number of parameters must match family declaration; expected 2
    • In the type instance declaration for ‘MkLink’
      In the instance declaration for ‘HasLink (View a)’
    |
126 |   type MkLink (View a) = MkLink (Get '[] ())
    |        ^^^^^^
```

I was able to reproduce this locally like so:

```bash
stack unpack miso-0.20.1.0 && cd miso-0.20.1.0
edit stack.yaml # add the following stack.yaml
stack build --test --bench --no-run-benchmarks
```

```yaml
# stack.yaml
resolver: nightly-2018-07-04
extra-deps:
- servant-0.14
- servant-lucid-0.8.1
```
