### ISSUE TITLE
Event handlers throw TypeError

### ISSUE THREAD

**Issue by y-taka-23** [dmjio/miso#459]
**Describe the bug**
In miso-0.21.2.0, firing events result in an uncaught exception`TypeError`.

**To Reproduce**

```yaml
resolver: lts-7.19
compiler: ghcjs-0.2.1.9007019_ghc-8.0.1
compiler-check: match-exact

packages:
- '.'
extra-deps:
- miso-0.21.2.0

setup-info:
  ghcjs:
    source:
      ghcjs-0.2.1.9007019_ghc-8.0.1:
         url: http://ghcjs.tolysz.org/ghc-8.0-2017-02-05-lts-7.19-9007019.tar.gz
         sha1: d2cfc25f9cda32a25a87d9af68891b2186ee52f9
```

```yaml
name:                app
version:             0.1.0.0

dependencies:
- base
- miso

executables:
  app:
    main:                Main.hs
```

```haskell
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE RecordWildCards   #-}

module Main where

import           Miso
import           Miso.String

type Model = Int

data Action = NoOp

main :: IO ()
main = startApp App {..}
  where
    initialAction = NoOp
    model = 0
    update = updateModel
    view = viewModel
    events = defaultEvents
    subs = []
    mountPoint = Nothing

updateModel :: Action -> Model -> Effect Action Model
updateModel NoOp m = noEff m

viewModel :: Model -> View Action
viewModel x = div_ [] [
      button_ [ onClick NoOp ] [ text "x" ]
    ]
```

Build it, click the `x` button, and you can see in the dev tool:

```
uncaught exception in Haskell thread: TypeError: Cannot read property 't' of undefined
rts.js:8350 TypeError: Cannot read property 't' of undefined
    at h$e (rts.js:20466)
    at h$$Eo (out.js:30262)
    at h$runThreadSlice (rts.js:9594)
    at h$runThreadSliceCatch (rts.js:9545)
    at h$mainLoop (rts.js:9538)
    at rts.js:2533
    at runIfPresent (rts.js:2552)
    at onGlobalMessage (rts.js:2600)
```

**Desktop**
Google Chrome 69.0.3497.100
