### ISSUE TITLE
miso for every OS

### ISSUE THREAD

**Issue by itmuckel** [dmjio/miso#568]
Hey guys! I debugged this the whole night (what is a nix build? cachix needs certificates?) and slept approx. 4 hours, but I got miso running under Windows through docker. And if it runs on Windows it probably runs everywhere else. 😃 

0. On Windows and Mac open your docker settings and increase the Memory and Swap (I use Memory=6GB and Swap=2GB), otherwise the container will be killed when exceeding the limit.
1. Create a new folder
2. Run `git clone https://github.com/dmjio/miso`
3. Do not cd into miso, but create two files:

`Dockerfile`:
```Dockerfile
FROM lnl7/nix:2.3.3 

RUN nix-env -iA \
        nixpkgs.curl \
        nixpkgs.jq \
        nixpkgs.git \
        nixpkgs.gnutar \
        nixpkgs.gzip \
        nixpkgs.libressl \
        nixpkgs.silver-searcher \
        nixpkgs.entr \
        nixpkgs.cabal-install

RUN nix-env -iA cachix -f https://cachix.org/api/v1/install
RUN SYSTEM_CERTIFICATE_PATH=$NIX_SSL_CERT_FILE USER=miso cachix use miso-haskell

COPY ./miso/sample-app /miso/sample-app 

WORKDIR /miso/sample-app

RUN nix-build
```

`docker-compose.yml`:
```yaml
version: "3.7"
services:
  app:
    build:
      context: .
    working_dir: /miso/sample-app
    command: [nix-shell, -A, env, default.nix, --run, "ag -l | (ENTR_INOTIFY_WORKAROUND=1 entr sh -c 'cabal build')"]
    volumes:
      - ./miso/sample-app:/miso/sample-app/
```

4. Run `docker-compose build`, this will take a long time
5. Run `docker-compose up`
6. `miso/sample-app` has now the build in `\dist-newstyle\build\x86_64-linux\ghcjs-8.6.0.1\app-0.1.0.0\x\app\build\app\app.jsexe` (isn't there a shortcut somewhere?!)
7. Open `index.html` on your host-machine and edit any file in `miso/sample-app` and docker will automatically rebuild the app
8. Have fun!

Notes:
- `ENTR_INOTIFY_WORKAROUND=1` was necessary, so file-changes on my host are recognized by entr. I think this is needed on Windows and MacOS.
- The Dockerfile executes nix-build, so you don't have to download all packages on every `docker-compose up`
- I don't know if this is necessary, but in `miso/sample-app` I have a `.gitignore` containing `/dist-newstyle`, so `ag` (silver-searcher) ignores the build output when looking for file changes.

Left to do:
- Automatically reload the browser on the host after a rebuild (don't know how)
