### ISSUE TITLE
Using hpack with jsaddle example

### ISSUE THREAD

**Issue by seanhess** [dmjio/miso#618]
I can't figure out how to use a package.yaml file with the jsaddle example. I'm terribly new to nix, so the errors don't make sense to me. It works for nix-build, but not for `nix-shell --run reload`

If you add the following package.yaml file to the sample-app-jsaddle example folder (Created by hpack-convert), it ignores it in favor of app.cabal. You can verify this by changing main to a nonexistent file. However, it _says_ it is using hpack in the output for some reason. 

```
name: app
version: '0.1.0.0'
synopsis: First miso app
category: Web
dependencies:
- base
- miso
executables:
  app:
    main: Main.hs
    when:
    - condition: '!impl(ghcjs)'
      dependencies:
      - jsaddle
      - jsaddle-warp
      - transformers
      - warp
      - websockets
```

If I then remove app.cabal, I get the following error:

```
building '/nix/store/jbf5c0pj66mq65pz7pbkx26q4wdrfw0d-cabal2nix-app.drv'...
installing
*** found package.yaml. Using hpack...
Loading /nix/store/mjxcpp9hrqj0rmh5d1rkmvnpwvj8bl2r-cabal-install-2.4.1.0/bin/cabal new-repl ...
Warning: The package list for 'hackage.haskell.org' is 24 days old.
Run 'cabal update' to get the latest list of available packages.
Resolving dependencies...
Build profile: -w ghc-8.6.5 -O1
In order, the following will be built (use -v for more details):
 - fake-package-0 (lib) (first run)
Configuring library for fake-package-0..
Preprocessing library for fake-package-0..
Warning: No exposed modules
GHCi, version 8.6.5: http://www.haskell.org/ghc/  :? for help

No files loaded, GHCi is not working properly.
Command: /nix/store/mjxcpp9hrqj0rmh5d1rkmvnpwvj8bl2r-cabal-install-2.4.1.0/bin/cabal new-repl
```

What is going on here? Any tips on how to debug this?
